
package bo.gob.sin.siat.facturacion.operaciones;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioFacturacionOperaciones", targetNamespace = "https://siat.impuestos.gob.bo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioFacturacionOperaciones {


    /**
     * 
     * @return
     *     returns bo.gob.sin.siat.facturacion.operaciones.RespuestaComunicacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verificarComunicacion", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.operaciones.VerificarComunicacion")
    @ResponseWrapper(localName = "verificarComunicacionResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.operaciones.VerificarComunicacionResponse")
    public RespuestaComunicacion verificarComunicacion();

    /**
     * 
     * @param solicitudRegistroPuntoVenta
     * @return
     *     returns bo.gob.sin.siat.facturacion.operaciones.RespuestaRegistroPuntoVenta
     */
    @WebMethod
    @WebResult(name = "RespuestaRegistroPuntoVenta", targetNamespace = "")
    @RequestWrapper(localName = "registroPuntoVenta", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.operaciones.RegistroPuntoVenta")
    @ResponseWrapper(localName = "registroPuntoVentaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.operaciones.RegistroPuntoVentaResponse")
    public RespuestaRegistroPuntoVenta registroPuntoVenta(
        @WebParam(name = "SolicitudRegistroPuntoVenta", targetNamespace = "")
        SolicitudRegistroPuntoVenta solicitudRegistroPuntoVenta);

    /**
     * 
     * @param solicitudPuntoVentaComisionista
     * @return
     *     returns bo.gob.sin.siat.facturacion.operaciones.RespuestaPuntoVentaComisionista
     */
    @WebMethod
    @WebResult(name = "RespuestaPuntoVentaComisionista", targetNamespace = "")
    @RequestWrapper(localName = "registroPuntoVentaComisionista", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.operaciones.RegistroPuntoVentaComisionista")
    @ResponseWrapper(localName = "registroPuntoVentaComisionistaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.operaciones.RegistroPuntoVentaComisionistaResponse")
    public RespuestaPuntoVentaComisionista registroPuntoVentaComisionista(
        @WebParam(name = "SolicitudPuntoVentaComisionista", targetNamespace = "")
        SolicitudPuntoVentaComisionista solicitudPuntoVentaComisionista);

    /**
     * 
     * @param solicitudOperaciones
     * @return
     *     returns bo.gob.sin.siat.facturacion.operaciones.RespuestaCierreSistemas
     */
    @WebMethod
    @WebResult(name = "RespuestaCierreSistemas", targetNamespace = "")
    @RequestWrapper(localName = "cierreOperacionesSistema", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.operaciones.CierreOperacionesSistema")
    @ResponseWrapper(localName = "cierreOperacionesSistemaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.operaciones.CierreOperacionesSistemaResponse")
    public RespuestaCierreSistemas cierreOperacionesSistema(
        @WebParam(name = "SolicitudOperaciones", targetNamespace = "")
        SolicitudOperaciones solicitudOperaciones);

    /**
     * 
     * @param solicitudConsultaEvento
     * @return
     *     returns bo.gob.sin.siat.facturacion.operaciones.RespuestaListaEventos
     */
    @WebMethod
    @WebResult(name = "RespuestaListaEventos", targetNamespace = "")
    @RequestWrapper(localName = "consultaEventoSignificativo", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.operaciones.ConsultaEventoSignificativo")
    @ResponseWrapper(localName = "consultaEventoSignificativoResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.operaciones.ConsultaEventoSignificativoResponse")
    public RespuestaListaEventos consultaEventoSignificativo(
        @WebParam(name = "SolicitudConsultaEvento", targetNamespace = "")
        SolicitudConsultaEvento solicitudConsultaEvento);

    /**
     * 
     * @param solicitudConsultaPuntoVenta
     * @return
     *     returns bo.gob.sin.siat.facturacion.operaciones.RespuestaConsultaPuntoVenta
     */
    @WebMethod
    @WebResult(name = "RespuestaConsultaPuntoVenta", targetNamespace = "")
    @RequestWrapper(localName = "consultaPuntoVenta", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.operaciones.ConsultaPuntoVenta")
    @ResponseWrapper(localName = "consultaPuntoVentaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.operaciones.ConsultaPuntoVentaResponse")
    public RespuestaConsultaPuntoVenta consultaPuntoVenta(
        @WebParam(name = "SolicitudConsultaPuntoVenta", targetNamespace = "")
        SolicitudConsultaPuntoVenta solicitudConsultaPuntoVenta);

    /**
     * 
     * @param solicitudEventoSignificativo
     * @return
     *     returns bo.gob.sin.siat.facturacion.operaciones.RespuestaListaEventos
     */
    @WebMethod
    @WebResult(name = "RespuestaListaEventos", targetNamespace = "")
    @RequestWrapper(localName = "registroEventoSignificativo", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.operaciones.RegistroEventoSignificativo")
    @ResponseWrapper(localName = "registroEventoSignificativoResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.operaciones.RegistroEventoSignificativoResponse")
    public RespuestaListaEventos registroEventoSignificativo(
        @WebParam(name = "SolicitudEventoSignificativo", targetNamespace = "")
        SolicitudEventoSignificativo solicitudEventoSignificativo);

    /**
     * 
     * @param solicitudCierrePuntoVenta
     * @return
     *     returns bo.gob.sin.siat.facturacion.operaciones.RespuestaCierrePuntoVenta
     */
    @WebMethod
    @WebResult(name = "RespuestaCierrePuntoVenta", targetNamespace = "")
    @RequestWrapper(localName = "cierrePuntoVenta", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.operaciones.CierrePuntoVenta")
    @ResponseWrapper(localName = "cierrePuntoVentaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.operaciones.CierrePuntoVentaResponse")
    public RespuestaCierrePuntoVenta cierrePuntoVenta(
        @WebParam(name = "SolicitudCierrePuntoVenta", targetNamespace = "")
        SolicitudCierrePuntoVenta solicitudCierrePuntoVenta);

}
