
package bo.gob.sin.siat.facturacion.codigos;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioFacturacionCodigos", targetNamespace = "https://siat.impuestos.gob.bo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioFacturacionCodigos {


    /**
     * 
     * @param solicitudVerificarNit
     * @return
     *     returns bo.gob.sin.siat.facturacion.codigos.RespuestaVerificarNit
     */
    @WebMethod
    @WebResult(name = "RespuestaVerificarNit", targetNamespace = "")
    @RequestWrapper(localName = "verificarNit", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.codigos.VerificarNit")
    @ResponseWrapper(localName = "verificarNitResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.codigos.VerificarNitResponse")
    public RespuestaVerificarNit verificarNit(
        @WebParam(name = "SolicitudVerificarNit", targetNamespace = "")
        SolicitudVerificarNit solicitudVerificarNit);

    /**
     * 
     * @return
     *     returns bo.gob.sin.siat.facturacion.codigos.RespuestaComunicacion
     */
    @WebMethod
    @WebResult(name = "RespuestaComunicacion", targetNamespace = "")
    @RequestWrapper(localName = "verificarComunicacion", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.codigos.VerificarComunicacion")
    @ResponseWrapper(localName = "verificarComunicacionResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.codigos.VerificarComunicacionResponse")
    public RespuestaComunicacion verificarComunicacion();

    /**
     * 
     * @param solicitudCuisMasivoSistemas
     * @return
     *     returns bo.gob.sin.siat.facturacion.codigos.RespuestaCuisMasivo
     */
    @WebMethod
    @WebResult(name = "RespuestaCuisMasivo", targetNamespace = "")
    @RequestWrapper(localName = "cuisMasivo", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.codigos.CuisMasivo")
    @ResponseWrapper(localName = "cuisMasivoResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.codigos.CuisMasivoResponse")
    public RespuestaCuisMasivo cuisMasivo(
        @WebParam(name = "SolicitudCuisMasivoSistemas", targetNamespace = "")
        SolicitudCuisMasivoSistemas solicitudCuisMasivoSistemas);

    /**
     * 
     * @param solicitudCufd
     * @return
     *     returns bo.gob.sin.siat.facturacion.codigos.RespuestaCufd
     */
    @WebMethod
    @WebResult(name = "RespuestaCufd", targetNamespace = "")
    @RequestWrapper(localName = "cufd", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.codigos.Cufd")
    @ResponseWrapper(localName = "cufdResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.codigos.CufdResponse")
    public RespuestaCufd cufd(
        @WebParam(name = "SolicitudCufd", targetNamespace = "")
        SolicitudCufd solicitudCufd);

    /**
     * 
     * @param solicitudNotificaRevocado
     * @return
     *     returns bo.gob.sin.siat.facturacion.codigos.RespuestaNotificaRevocado
     */
    @WebMethod
    @WebResult(name = "RespuestaNotificaRevocado", targetNamespace = "")
    @RequestWrapper(localName = "notificaCertificadoRevocado", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.codigos.NotificaCertificadoRevocado")
    @ResponseWrapper(localName = "notificaCertificadoRevocadoResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.codigos.NotificaCertificadoRevocadoResponse")
    public RespuestaNotificaRevocado notificaCertificadoRevocado(
        @WebParam(name = "SolicitudNotificaRevocado", targetNamespace = "")
        SolicitudNotifcaRevocado solicitudNotificaRevocado);

    /**
     * 
     * @param solicitudCuis
     * @return
     *     returns bo.gob.sin.siat.facturacion.codigos.RespuestaCuis
     */
    @WebMethod
    @WebResult(name = "RespuestaCuis", targetNamespace = "")
    @RequestWrapper(localName = "cuis", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.codigos.Cuis")
    @ResponseWrapper(localName = "cuisResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.codigos.CuisResponse")
    public RespuestaCuis cuis(
        @WebParam(name = "SolicitudCuis", targetNamespace = "")
        SolicitudCuis solicitudCuis);

    /**
     * 
     * @param solicitudCufdMasivo
     * @return
     *     returns bo.gob.sin.siat.facturacion.codigos.RespuestaCufdMasivo
     */
    @WebMethod
    @WebResult(name = "RespuestaCufdMasivo", targetNamespace = "")
    @RequestWrapper(localName = "cufdMasivo", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.codigos.CufdMasivo")
    @ResponseWrapper(localName = "cufdMasivoResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.facturacion.codigos.CufdMasivoResponse")
    public RespuestaCufdMasivo cufdMasivo(
        @WebParam(name = "SolicitudCufdMasivo", targetNamespace = "")
        SolicitudCufdMasivo solicitudCufdMasivo);

}
