
package bo.gob.sin.siat.servicio.facturacion.DocumentoAjuste;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioRecepcionCompras", targetNamespace = "https://siat.impuestos.gob.bo/ServicioRecepcionCompras", wsdlLocation = "file:/home/antonio/Documents/Proyect/farmacia_app/backend/src/main/resources/wsdl/ServicioRecepcionCompras.wsdl")
public class ServicioRecepcionCompras
    extends Service
{

    private final static URL SERVICIORECEPCIONCOMPRAS_WSDL_LOCATION;
    private final static WebServiceException SERVICIORECEPCIONCOMPRAS_EXCEPTION;
    private final static QName SERVICIORECEPCIONCOMPRAS_QNAME = new QName("https://siat.impuestos.gob.bo/ServicioRecepcionCompras", "ServicioRecepcionCompras");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/antonio/Documents/Proyect/farmacia_app/backend/src/main/resources/wsdl/ServicioRecepcionCompras.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIORECEPCIONCOMPRAS_WSDL_LOCATION = url;
        SERVICIORECEPCIONCOMPRAS_EXCEPTION = e;
    }

    public ServicioRecepcionCompras() {
        super(__getWsdlLocation(), SERVICIORECEPCIONCOMPRAS_QNAME);
    }

    public ServicioRecepcionCompras(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIORECEPCIONCOMPRAS_QNAME, features);
    }

    public ServicioRecepcionCompras(URL wsdlLocation) {
        super(wsdlLocation, SERVICIORECEPCIONCOMPRAS_QNAME);
    }

    public ServicioRecepcionCompras(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIORECEPCIONCOMPRAS_QNAME, features);
    }

    public ServicioRecepcionCompras(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioRecepcionCompras(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioFacturacion
     */
    @WebEndpoint(name = "ServicioFacturacionPort")
    public ServicioFacturacion getServicioFacturacionPort() {
        return super.getPort(new QName("https://siat.impuestos.gob.bo/ServicioRecepcionCompras", "ServicioFacturacionPort"), ServicioFacturacion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioFacturacion
     */
    @WebEndpoint(name = "ServicioFacturacionPort")
    public ServicioFacturacion getServicioFacturacionPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://siat.impuestos.gob.bo/ServicioRecepcionCompras", "ServicioFacturacionPort"), ServicioFacturacion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIORECEPCIONCOMPRAS_EXCEPTION!= null) {
            throw SERVICIORECEPCIONCOMPRAS_EXCEPTION;
        }
        return SERVICIORECEPCIONCOMPRAS_WSDL_LOCATION;
    }

}
