
package bo.gob.sin.siat.servicio.facturacion.CompraVenta;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioFacturacion", targetNamespace = "https://siat.impuestos.gob.bo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioFacturacion {


    /**
     * 
     * @param solicitudServicioAnulacionDocumentoAjuste
     * @return
     *     returns bo.gob.sin.siat.servicio.facturacion.CompraVenta.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "anulacionDocumentoAjuste", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.servicio.facturacion.CompraVenta.AnulacionDocumentoAjuste")
    @ResponseWrapper(localName = "anulacionDocumentoAjusteResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.servicio.facturacion.CompraVenta.AnulacionDocumentoAjusteResponse")
    public RespuestaRecepcion anulacionDocumentoAjuste(
        @WebParam(name = "SolicitudServicioAnulacionDocumentoAjuste", targetNamespace = "")
        SolicitudAnulacion solicitudServicioAnulacionDocumentoAjuste);

    /**
     * 
     * @param solicitudServicioReversionAnulacionDocumentoAjuste
     * @return
     *     returns bo.gob.sin.siat.servicio.facturacion.CompraVenta.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "reversionAnulacionDocumentoAjuste", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.servicio.facturacion.CompraVenta.ReversionAnulacionDocumentoAjuste")
    @ResponseWrapper(localName = "reversionAnulacionDocumentoAjusteResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.servicio.facturacion.CompraVenta.ReversionAnulacionDocumentoAjusteResponse")
    public RespuestaRecepcion reversionAnulacionDocumentoAjuste(
        @WebParam(name = "SolicitudServicioReversionAnulacionDocumentoAjuste", targetNamespace = "")
        SolicitudReversionAnulacion solicitudServicioReversionAnulacionDocumentoAjuste);

    /**
     * 
     * @return
     *     returns bo.gob.sin.siat.servicio.facturacion.CompraVenta.RespuestaComunicacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verificarComunicacion", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.servicio.facturacion.CompraVenta.VerificarComunicacion")
    @ResponseWrapper(localName = "verificarComunicacionResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.servicio.facturacion.CompraVenta.VerificarComunicacionResponse")
    public RespuestaComunicacion verificarComunicacion();

    /**
     * 
     * @param solicitudServicioRecepcionDocumentoAjuste
     * @return
     *     returns bo.gob.sin.siat.servicio.facturacion.CompraVenta.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "recepcionDocumentoAjuste", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.servicio.facturacion.CompraVenta.RecepcionDocumentoAjuste")
    @ResponseWrapper(localName = "recepcionDocumentoAjusteResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.servicio.facturacion.CompraVenta.RecepcionDocumentoAjusteResponse")
    public RespuestaRecepcion recepcionDocumentoAjuste(
        @WebParam(name = "SolicitudServicioRecepcionDocumentoAjuste", targetNamespace = "")
        SolicitudRecepcionFactura solicitudServicioRecepcionDocumentoAjuste);

    /**
     * 
     * @param solicitudServicioVerificacionEstadoDocumentoAjuste
     * @return
     *     returns bo.gob.sin.siat.servicio.facturacion.CompraVenta.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "verificacionEstadoDocumentoAjuste", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.servicio.facturacion.CompraVenta.VerificacionEstadoDocumentoAjuste")
    @ResponseWrapper(localName = "verificacionEstadoDocumentoAjusteResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "bo.gob.sin.siat.servicio.facturacion.CompraVenta.VerificacionEstadoDocumentoAjusteResponse")
    public RespuestaRecepcion verificacionEstadoDocumentoAjuste(
        @WebParam(name = "SolicitudServicioVerificacionEstadoDocumentoAjuste", targetNamespace = "")
        SolicitudVerificacionEstado solicitudServicioVerificacionEstadoDocumentoAjuste);

}
